name: toast_tiku
description: Toast Tiku written in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  provider: ^6.0.0
  get_it: ^7.2.0
  hive_flutter: ^1.0.0
  flutter_neumorphic_plus: ^3.3.0
  dio: ^5.4.3+1
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0
  extended_image: ^8.2.0
  url_launcher: ^6.2.6
  countly_flutter: ^24.4.0
  logging: ^1.0.2
  flutter_material_color_picker: ^1.1.0+2
  r_upgrade: 0.3.8
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

