// This file is generated by ./make.dart

class BuildData {
  static const String name = "Toast题库";
  static const int build = 12;
  static const String engine =
      "Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git\nFramework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700\nEngine • revision 241c87ad80\nTools • Dart 2.13.4\n";
  static const String buildAt = "2021-08-06 14:45:06.050118";
  static const int modifications = 16;
}
